import { 
  Coffee, 
  Flame, 
  Tent, 
  Snowflake, 
  Lightbulb, 
  Car, 
  Heart, 
  Music, 
  Package,
  Utensils,
  Pizza,
  Cake,
  Apple,
  Beef,
  Salad,
  Soup,
  Sandwich,
  Cookie,
  IceCream,
  Milk,
  Wine,
  Beer,
  CupSoda,
  Popcorn,
  Croissant,
  Egg,
  Fish,
  Cherry,
  Grape,
  Banana,
  Citrus,
  Carrot,
  Home,
  Building,
  Building2,
  Warehouse,
  Store,
  Hotel,
  Castle,
  Church,
  School,
  Hospital,
  Mountain,
  MountainSnow,
  Trees,
  TreePalm,
  TreeDeciduous,
  TreePine,
  Flower,
  Flower2,
  Leaf,
  Clover,
  Sun,
  Moon,
  Star,
  Cloud,
  CloudRain,
  CloudSnow,
  Wind,
  Rainbow,
  Umbrella,
  Thermometer,
  Map,
  MapPin,
  Compass,
  Globe,
  Navigation,
  Signpost,
  Route,
  Milestone,
  Truck,
  Bus,
  Train,
  Plane,
  Ship,
  Bike,
  Shirt,
  Footprints,
  Glasses,
  Watch,
  Crown,
  Gem,
  Scissors,
  Ruler,
  Pencil,
  Pen,
  Highlighter,
  Paperclip,
  Bookmark,
  Book,
  BookOpen,
  GraduationCap,
  Backpack,
  Briefcase,
  Folder,
  FileText,
  Clipboard,
  Camera,
  Video,
  Film,
  Tv,
  Monitor,
  Laptop,
  Tablet,
  Smartphone,
  Headphones,
  Speaker,
  Mic,
  Radio,
  Volume2,
  Bell,
  AlarmClock,
  Phone,
  Mail,
  MessageCircle,
  MessageSquare,
  Inbox,
  Send,
  AtSign,
  Hash,
  Link,
  QrCode,
  Wifi,
  Bluetooth,
  Signal,
  Satellite,
  Cast,
  Download,
  Upload,
  Key,
  Lock,
  Unlock,
  Shield,
  ShieldCheck,
  Eye,
  EyeOff,
  Fingerprint,
  Scan,
  Activity,
  Stethoscope,
  Syringe,
  Pill,
  Bandage,
  Brain,
  Dumbbell,
  Trophy,
  Medal,
  Target,
  Flag,
  Award,
  Dice1,
  Dice2,
  Dice3,
  Dice4,
  Dice5,
  Dice6,
  Puzzle,
  Gamepad2,
  Palette,
  Brush,
  PaintBucket,
  Stamp,
  Crop,
  Layers,
  Shapes,
  Circle,
  Square,
  Triangle,
  Hexagon,
  Octagon,
  Pentagon,
  Diamond,
  Handshake,
  Users,
  User,
  UserPlus,
  Baby,
  PersonStanding,
  Accessibility,
  Dog,
  Cat,
  Bird,
  Bug,
  Rabbit,
  Turtle,
  Wrench,
  Hammer,
  Axe,
  Shovel,
  Flashlight,
  Plug,
  Battery,
  BatteryCharging,
  Zap,
  Power,
  Lamp,
  Fan,
  Droplet,
  Droplets,
  Waves,
  Anchor,
  Sailboat,
  Shell,
  FireExtinguisher,
  Tornado,
  Sunrise,
  Sunset,
  Gift,
  PartyPopper,
  Ribbon,
  Box,
  ShoppingBag,
  ShoppingCart,
  ShoppingBasket,
  Wallet,
  CreditCard,
  Banknote,
  Coins,
  PiggyBank,
  Receipt,
  Calculator,
  Clock,
  Timer,
  Hourglass,
  Calendar,
  CalendarDays,
  CalendarCheck,
  Rocket,
  Construction,
  HardHat,
  Recycle,
  Sprout,
  Wheat,
  Microscope,
  Telescope,
  Binoculars,
  Search,
  ZoomIn,
  ZoomOut,
  Focus,
  Crosshair,
  Sparkles,
  Wand2,
  BadgeCheck,
  type LucideIcon 
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  coffee: Coffee,
  flame: Flame,
  tent: Tent,
  snowflake: Snowflake,
  lightbulb: Lightbulb,
  car: Car,
  heart: Heart,
  music: Music,
  package: Package,
  utensils: Utensils,
  pizza: Pizza,
  cake: Cake,
  apple: Apple,
  beef: Beef,
  salad: Salad,
  soup: Soup,
  sandwich: Sandwich,
  cookie: Cookie,
  "ice-cream": IceCream,
  milk: Milk,
  wine: Wine,
  beer: Beer,
  "cup-soda": CupSoda,
  popcorn: Popcorn,
  croissant: Croissant,
  egg: Egg,
  fish: Fish,
  cherry: Cherry,
  grape: Grape,
  banana: Banana,
  citrus: Citrus,
  carrot: Carrot,
  home: Home,
  building: Building,
  "building-2": Building2,
  warehouse: Warehouse,
  store: Store,
  hotel: Hotel,
  castle: Castle,
  church: Church,
  school: School,
  hospital: Hospital,
  mountain: Mountain,
  "mountain-snow": MountainSnow,
  trees: Trees,
  "tree-palm": TreePalm,
  "tree-deciduous": TreeDeciduous,
  "tree-pine": TreePine,
  flower: Flower,
  "flower-2": Flower2,
  leaf: Leaf,
  clover: Clover,
  sun: Sun,
  moon: Moon,
  star: Star,
  cloud: Cloud,
  "cloud-rain": CloudRain,
  "cloud-snow": CloudSnow,
  wind: Wind,
  rainbow: Rainbow,
  umbrella: Umbrella,
  thermometer: Thermometer,
  map: Map,
  "map-pin": MapPin,
  compass: Compass,
  globe: Globe,
  navigation: Navigation,
  signpost: Signpost,
  route: Route,
  milestone: Milestone,
  truck: Truck,
  bus: Bus,
  train: Train,
  plane: Plane,
  ship: Ship,
  bike: Bike,
  shirt: Shirt,
  footprints: Footprints,
  glasses: Glasses,
  watch: Watch,
  crown: Crown,
  gem: Gem,
  scissors: Scissors,
  ruler: Ruler,
  pencil: Pencil,
  pen: Pen,
  highlighter: Highlighter,
  paperclip: Paperclip,
  bookmark: Bookmark,
  book: Book,
  "book-open": BookOpen,
  "graduation-cap": GraduationCap,
  backpack: Backpack,
  briefcase: Briefcase,
  folder: Folder,
  "file-text": FileText,
  clipboard: Clipboard,
  camera: Camera,
  video: Video,
  film: Film,
  tv: Tv,
  monitor: Monitor,
  laptop: Laptop,
  tablet: Tablet,
  smartphone: Smartphone,
  headphones: Headphones,
  speaker: Speaker,
  mic: Mic,
  radio: Radio,
  "volume-2": Volume2,
  bell: Bell,
  "alarm-clock": AlarmClock,
  phone: Phone,
  mail: Mail,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  inbox: Inbox,
  send: Send,
  "at-sign": AtSign,
  hash: Hash,
  link: Link,
  "qr-code": QrCode,
  wifi: Wifi,
  bluetooth: Bluetooth,
  signal: Signal,
  satellite: Satellite,
  cast: Cast,
  download: Download,
  upload: Upload,
  key: Key,
  lock: Lock,
  unlock: Unlock,
  shield: Shield,
  "shield-check": ShieldCheck,
  eye: Eye,
  "eye-off": EyeOff,
  fingerprint: Fingerprint,
  scan: Scan,
  activity: Activity,
  stethoscope: Stethoscope,
  syringe: Syringe,
  pill: Pill,
  bandage: Bandage,
  brain: Brain,
  dumbbell: Dumbbell,
  trophy: Trophy,
  medal: Medal,
  target: Target,
  flag: Flag,
  award: Award,
  "dice-1": Dice1,
  "dice-2": Dice2,
  "dice-3": Dice3,
  "dice-4": Dice4,
  "dice-5": Dice5,
  "dice-6": Dice6,
  puzzle: Puzzle,
  "gamepad-2": Gamepad2,
  palette: Palette,
  brush: Brush,
  "paint-bucket": PaintBucket,
  stamp: Stamp,
  crop: Crop,
  layers: Layers,
  shapes: Shapes,
  circle: Circle,
  square: Square,
  triangle: Triangle,
  hexagon: Hexagon,
  octagon: Octagon,
  pentagon: Pentagon,
  diamond: Diamond,
  handshake: Handshake,
  users: Users,
  user: User,
  "user-plus": UserPlus,
  baby: Baby,
  "person-standing": PersonStanding,
  accessibility: Accessibility,
  dog: Dog,
  cat: Cat,
  bird: Bird,
  bug: Bug,
  rabbit: Rabbit,
  turtle: Turtle,
  wrench: Wrench,
  hammer: Hammer,
    axe: Axe,
  shovel: Shovel,
  flashlight: Flashlight,
  plug: Plug,
  battery: Battery,
  "battery-charging": BatteryCharging,
  zap: Zap,
  power: Power,
  lamp: Lamp,
  fan: Fan,
  droplet: Droplet,
  droplets: Droplets,
  waves: Waves,
  anchor: Anchor,
  sailboat: Sailboat,
  shell: Shell,
    "fire-extinguisher": FireExtinguisher,
  tornado: Tornado,
  sunrise: Sunrise,
  sunset: Sunset,
  gift: Gift,
  "party-popper": PartyPopper,
  ribbon: Ribbon,
  box: Box,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  "shopping-basket": ShoppingBasket,
  wallet: Wallet,
  "credit-card": CreditCard,
  banknote: Banknote,
  coins: Coins,
  "piggy-bank": PiggyBank,
  receipt: Receipt,
  calculator: Calculator,
  clock: Clock,
  timer: Timer,
  hourglass: Hourglass,
  calendar: Calendar,
  "calendar-days": CalendarDays,
  "calendar-check": CalendarCheck,
    rocket: Rocket,
  construction: Construction,
  "hard-hat": HardHat,
  recycle: Recycle,
  sprout: Sprout,
  wheat: Wheat,
  microscope: Microscope,
  telescope: Telescope,
  binoculars: Binoculars,
  search: Search,
  "zoom-in": ZoomIn,
  "zoom-out": ZoomOut,
  focus: Focus,
  crosshair: Crosshair,
  sparkles: Sparkles,
  "wand-2": Wand2,
  "badge-check": BadgeCheck,
};

interface CategoryIconProps {
  icon: string;
  className?: string;
  color?: string;
}

export function CategoryIcon({ icon, className = "h-5 w-5", color }: CategoryIconProps) {
  const Icon = iconMap[icon] || Package;
  return <Icon className={className} style={color ? { color } : undefined} />;
}

export const AVAILABLE_ICON_NAMES = Object.keys(iconMap);
